services:
  app:
    image: store-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: store-frontend

  server:
    image: store-backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    container_name: store-backend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-store
    depends_on:
      - app
      - server
